import type { Metadata } from "next";
import "./globals.css";
import { Public_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import LoadingClientWrapper from "@/components/LoadingClientWrapper";
import { Provider as JotaiProvider } from "jotai";
import DemoDataRefresher from "@/components/DemoDataRefresher";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-public-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${publicSans.className}`}>
          <JotaiProvider>
            <LoadingClientWrapper>
              <DemoDataRefresher></DemoDataRefresher>
              <main>{children}</main>
            </LoadingClientWrapper>
          </JotaiProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
