import type { Metadata } from "next";
import "./globals.css";
import { Public_Sans } from "next/font/google";
import { ConvexClientProvider } from "@/features/auth/components/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import Providers from "./Providers";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-public-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <ConvexAuthNextjsServerProvider>
        <html lang="en">
          <body className={publicSans.className}>
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </body>
        </html>
      </ConvexAuthNextjsServerProvider>
    </Providers>
  );
}
